### ISSUE TITLE
Sekoia Balance Checker Not Working

### ISSUE THREAD

**Issue by 0xYao** [sekoia-virtuals/sekoia-web#1]
I connected with a wallet with a lot of $sekoia balance, but the website says I don't have any

p.s I was using a Rabby wallet on Brave

**Comment by Gordonhills** [comment]
Hello @0xYao 
You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID SEK07638
Please see the link below to our dedicated support line:
[Sekoia wallet Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by sekoia-virtuals** [comment]
Submit a pull request :)

**Comment by 0xYao** [comment]
> Submit a pull request :)

Check out this PR

https://github.com/sekoia-virtuals/sekoia-web/pull/4

**Comment by sekoia-virtuals** [comment]
thanks for fixing this! It would be great to work with you. Mind shooting an email: info@sekoia.vc

**Comment by 0xYao** [comment]
> thanks for fixing this! It would be great to work with you. Mind shooting an email: info@sekoia.vc

Of course, just sent an email
