### ISSUE TITLE
Convert plain HTML to React

### ISSUE THREAD

**Issue by 0xYao** [sekoia-virtuals/sekoia-web#3]
Plain HTML code is hard to maintain. React is more modern and is easier to add and update code. It will enable more developers to collaborate with the project.

I am happy to lead this change.

**Comment by sekoia-virtuals** [comment]
Work is underway to move this to a Node frontend+backend. And very much agreed that plain HTML+JS will only get you so far. We would welcome any and all support. Tyvm!
